apiVersion: v1
kind: Service
metadata:
  namespace: 4al1-groupe-9
  name: frontend-service-4al1-groupe-9
spec:
  selector:
    app: frontend-4al1-groupe-9
  ports:
  - port: {{ .Values.ports.ingress }}
    targetPort: {{ .Values.ports.container }}