name: Back

on:
  pull_request:
    branches: [ develop ]
    
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
        
      - name: install dependencies
        run: npm install
