name: Build & Deploy

on:
  push:
    branches: [ develop ]
    
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
        
      - name: install dependencies
        run: npm install
        
      - name: Build front
        run: npm run build
  
  deploy:
    needs: build
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: titeshi
          password: u@!8t2AcJ7
          logout: true

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: titeshi/cepasimal-front
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: develop  
          labels: develop
