name: Build & Deploy

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]
    
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      
      - run: cat > kubeconfig.yml
      
      - run: touch kubeconfig.yml
            ${{ secrets.KUBECONFIG }}
        
      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '18.12.1'
        
      - name: Install dependencies
        run: npm install
        
      - name: Build front
        run: npm run build

  lint: 
    if: ${{github.event_name == 'pull_request'}}
    needs: [build]
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Install Eslint
        run: npm install eslint

      - name: Check lint
        run: npm run lint

  test:
    if: ${{github.event_name == 'pull_request'}}
    needs: [lint]
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Install Cypress
        run: npm install cypress

      - name: Check unit test
        run: npm run test:unit

      - name: Check e2e test
        run: npm run test:e2e
  
  docker:
    if: ${{github.event_name == 'push'}}
    needs: [build]
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: titeshi/cepasimal-front:1.0.2
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: titeshi/cepasimal-front:1.0.2

  deploy:
    if: ${{github.event_name == 'push'}}
    needs: [docker]
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          
      - name: Create kubeconfig file
        run: cat > kubeconfig.yml 
              ${{ secrets.KUBECONFIG }}

      - name: Update Helm
        run: helm upgrade --kubeconfig ./kubeconfig.yml 4al1-g9-front-chart ./chart/
